di: Allow to make Rust types anonymous
aya-rs/bpf-linker pull request #133
Opened 2023-10-08 13:01 UTC by vadorovsky

Rust does not provide a possibility of defining anonymous types, but we need it to produce BTF acceptable by the kernel for BTF maps.

As a workaround, use our DI sanitizer to make type anonymous if it contains an `_anon` field. To not affect the layout of the struct, it should be defined as `PhantomData`, e.g.

```rust
pub struct Foo {
    _anon: PhantomData<u8>,
    something: u32,
}
```

2023-10-08 14:15 UTC, tamird approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133)* status: all files reviewed, 1 unresolved discussion (waiting on @vadorovsky)

___
*[`src/llvm/di.rs` line 89 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgEd0QNEeu_3PPgQ9_k:-NgEd0QO1ACy5_ja2pnA:b-6kvvn1) ([raw file](https://github.com/aya-rs/bpf-linker/blob/60ce107a15333946ba0116297af30c9fd27ae6f4/src/llvm/di.rs#L89)):*
> ```XML
>                             .unwrap();
> 
>                         if name.starts_with("HashMap<") {
> ```

did you mean to include this change? can you explain why in the commit message?


<!-- Sent from Reviewable.io -->

2023-10-08 16:10 UTC, vadorovsky commented
*[`src/llvm/di.rs` line 89 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgEd0QNEeu_3PPgQ9_k:-NgF20mMCd533FSilciU:b36u126) ([raw file](https://github.com/aya-rs/bpf-linker/blob/60ce107a15333946ba0116297af30c9fd27ae6f4/src/llvm/di.rs#L89)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

did you mean to include this change? can you explain why in the commit message?
</blockquote></details>

That's the whole point of this change :stuck_out_tongue: - to have an explicit marker for making struct anonymous instead of hard-coding the struct names. After all, all maps types need to be anonymous. I will make sure to clear that up in the commit message.


<!-- Sent from Reviewable.io -->

2023-10-08 16:53 UTC, tamird commented
> _[`src/llvm/di.rs` line 89 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgEd0QNEeu_3PPgQ9_k:-NgF20mMCd533FSilciU:b36u126) ([raw file](https://github.com/aya-rs/bpf-linker/blob/60ce107a15333946ba0116297af30c9fd27ae6f4/src/llvm/di.rs#L89)):_
> 
> Previously, tamird (Tamir Duberstein) wrote…
> That's the whole point of this change 😛 - to have an explicit marker for making struct anonymous instead of hard-coding the struct names. After all, all maps types need to be anonymous. I will make sure to clear that up in the commit message.

I think you're saying that the hash map happens to have a field called _anon? I think we should have a link to the source?

2023-10-08 19:46 UTC, vadorovsky commented
> > _[`src/llvm/di.rs` line 89 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgEd0QNEeu_3PPgQ9_k:-NgF20mMCd533FSilciU:b36u126) ([raw file](https://github.com/aya-rs/bpf-linker/blob/60ce107a15333946ba0116297af30c9fd27ae6f4/src/llvm/di.rs#L89)):_
> > Previously, tamird (Tamir Duberstein) wrote…
> > That's the whole point of this change 😛 - to have an explicit marker for making struct anonymous instead of hard-coding the struct names. After all, all maps types need to be anonymous. I will make sure to clear that up in the commit message.
> 
> I think you're saying that the hash map happens to have a field called _anon? I think we should have a link to the source?

It doesn't have it yet, but yes, once this change is merged, we can start introducing the `AyaBtfMapMarker` type to Aya. I'm planning to work on it the following week.

2023-10-08 19:57 UTC, tamird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-:-NgFrNmQ8A5js9FOky2L:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @vadorovsky)

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFphoK5Eu5toy-o71c):*
Previously
___
*[`src/llvm/di.rs` line 23 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFptWFCILYDkViuii2:-NgFptWFCILYDkViuii3:b-gmxtbt) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L23)):*
> ```XML
> const MAX_KSYM_NAME_LEN: usize = 128;
> 
> #[repr(u32)]
> ```

i think given the `From` impl below, you can remove this and the explicit variant values
___
*[`src/llvm/di.rs` line 30 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFqC0F6BMh0uIxpeSR:-NgFqC0F6BMh0uIxpeSS:bglg86e) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L30)):*
> ```XML
> }
> 
> impl From<DICompositeTypeOperand> for u32 {
> ```

perhaps instead of this From impl we should have a typed wrapper around `LLVMGetOperand` and `LLVMReplaceMDNodeOperandWith`?
___
*[`src/llvm/di.rs` line 232 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFrJBoAgrKD-Db_RZN:-NgFrJBoAgrKD-Db_RZO:b20364e) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L232)):*
> ```XML
>                                         // TODO(vadorovsky): Use the helper from
>                                         // https://github.com/aya-rs/bpf-linker/pull/120
>                                         // This field indicates that the struct should be anonymized.
> ```

this is sort of the same comment as below - combine them?


<!-- Sent from Reviewable.io -->

2023-10-18 12:42 UTC, vadorovsky reviewed
Sorry for following up late and thanks for review @tamird.

> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-:-Nh1nb3-0Y7Fl5vBJRPm:b-6zr7uv)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @tamird)

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFphoK5Eu5toy-o71c):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Previously
</blockquote></details>

Done.
___
*[`src/llvm/di.rs` line 23 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFptWFCILYDkViuii2:-Nh0b0tjAEHepU_iklAf:b-5xhxsh) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i think given the `From` impl below, you can remove this and the explicit variant values
</blockquote></details>

Actually, I removed the`From` impl and just did `as u32` on the enum variants, I think it's cleaner that way. Let me know whether you agree.
___
*[`src/llvm/di.rs` line 30 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFqC0F6BMh0uIxpeSR:-Nh0bA7h8YeY8gsufMfE:bti6frt) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps instead of this From impl we should have a typed wrapper around `LLVMGetOperand` and `LLVMReplaceMDNodeOperandWith`?
</blockquote></details>

I like the idea, done. This way I also realized one mistake (`Type = 3` should belong to `DIDerivedType`, not `DICompositeType`).

That said, I didn't provide typed wrappers for exactly everything in this module, I wrapped only parts directly related to my change (`DIDerivedType` and `DICompositeType` instances which are members of other `DICompositeType`s). Honestly, I'm still unhappy with all unwraps and unsafes, but I don't want to bloat this PR with too heavy refactors. I have an intention to do so in a separate PR. I started working on it [on my branch](https://github.com/vadorovsky/bpf-linker/tree/di-refactor).
___
*[`src/llvm/di.rs` line 232 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFrJBoAgrKD-Db_RZN:-Nh1nT65661uxKL8zCY-:bb6un1j) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L232)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is sort of the same comment as below - combine them?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-18 14:32 UTC, tamird requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133)* status: all files reviewed, 2 unresolved discussions (waiting on @vadorovsky)

___
*[`src/llvm/di.rs` line 23 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFptWFCILYDkViuii2:-Nh2ABT6D-tr-kRruznh:b9huoy5) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L23)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

Actually, I removed the`From` impl and just did `as u32` on the enum variants, I think it's cleaner that way. Let me know whether you agree.
</blockquote></details>

Sounds good to me. Can you add a comment that links to the relevant values in the LLVM source or docs? It would be good to be able to check that the variants and their values make sense.
___
*[`src/llvm/di.rs` line 232 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFrJBoAgrKD-Db_RZN:-Nh2BgUf0S3ILyQYfmac:b4wxio) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L232)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

Done
</blockquote></details>

https://github.com/aya-rs/bpf-linker/pull/120 is merged now, should this be using DIType::name?
___
*[`src/llvm/di.rs` line 154 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-Nh2B9cV40F5Vux4bvcD:-Nh2B9cV40F5Vux4bvcE:b12amal) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b924f81ccf6178d32bb20e3331040b96b639fc91/src/llvm/di.rs#L154)):*
> ```XML
>         let empty = to_mdstring(self.context, "");
> 
>         match metadata_kind {
> ```

another idea for a future improvement is to have a method that takes a `LLVMValueRef` and internally checks the metadata kind and returns an enum that is either a DICompositeType, or DiDerivedOperandType, or whatever other types.


<!-- Sent from Reviewable.io -->

2023-10-18 15:57 UTC, vadorovsky commented
*[`src/llvm/di.rs` line 154 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-Nh2B9cV40F5Vux4bvcD:-Nh2UKws2ApJcEJuInhQ:b-2ndykc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b924f81ccf6178d32bb20e3331040b96b639fc91/src/llvm/di.rs#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

another idea for a future improvement is to have a method that takes a `LLVMValueRef` and internally checks the metadata kind and returns an enum that is either a DICompositeType, or DiDerivedOperandType, or whatever other types.
</blockquote></details>

I was thinking about something similar - having a safe wrapper around `LLVMValueRef`/`LLVMMetadataRef` which has a method returning a data-carrying enum with a concrete type of the metadata kind. See:

https://github.com/vadorovsky/bpf-linker/blob/di-refactor/src/llvm/mod.rs#L367-L423

This still needs some work and I'm not sure if representing the inheritance of LLVM types via fields is a good solution (the function I linked is quite a mess to read with these nested fields). Maybe I should just flatten these types and include `value: LLVMValueRef` or `metadata: LLVMMetadataRef` directly in each struct.


<!-- Sent from Reviewable.io -->

2023-10-19 23:16 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/di.rs` line 23 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFptWFCILYDkViuii2:-Nh9DWiIBCcUiM2m6kYc:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Sounds good to me. Can you add a comment that links to the relevant values in the LLVM source or docs? It would be good to be able to check that the variants and their values make sense.
</blockquote></details>

Done.
___
*[`src/llvm/di.rs` line 232 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/133#-NgFrJBoAgrKD-Db_RZN:-Nh9DY9H3rqJA3HdkZrE:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/141f1613440a047fcacb5b9135e1c653c00ae439/src/llvm/di.rs#L232)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

https://github.com/aya-rs/bpf-linker/pull/120 is merged now, should this be using DIType::name?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 00:32 UTC, tamird approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2023-10-22 18:31 UTC, merged