di: Sanitize data carrying enums correctly
aya-rs/bpf-linker pull request #151
Opened 2023-11-22 00:09 UTC by vadorovsky

Data carrying enums are causing a crash of the BPF Assembly Printer pass. As a workaround, we were always replacing the elements of that enum metadata with an empty MDNode.

However, #142 broke this behavior by calling `replace_elements` on a wrong composite type - it was calling it on the inner one (data carrying field), instead of the outer one (enum). This change fixes it.

2023-11-22 00:13 UTC, vadorovsky commented on src/llvm/di.rs
> +                            // TODO(vadorovsky): We might be leaking memory here,
Still in doubt how to handle that properly

2023-11-27 16:26 UTC, tamird requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/151)* status: all files reviewed, 2 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`src/llvm/di.rs` line 576 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/151#-NkBzgby4mIPtNg_Zlgv:-NkElNL2-6UO5AOJUrlj:bsxvogr) ([raw file](https://github.com/aya-rs/bpf-linker/blob/eb86a21f3dfd9ef9df0ab222ad7296a7bc1c7a8d/src/llvm/di.rs#L576)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

This is exactly what's written here? :D
</blockquote></details>

It should just be "another"
___
*[`src/llvm/di.rs` line 648 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/151#gh-1401354824:-NkGaQaIEw2147Ft6Ulv:b-r6wo6i) ([raw file](https://github.com/aya-rs/bpf-linker/blob/eb86a21f3dfd9ef9df0ab222ad7296a7bc1c7a8d/src/llvm/di.rs#L648)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

No, it doesn't return anything.

The only thing it does is calling `LLVMReplaceMDNodeOperandWith` to replace the `Elements` operand of the given value with an empty MDNode. My concern (and yours also, you shared it in previous reviews) was that we are not freeing the old elements. But we discussed this with Alessandro yesterday (see the Discord link) and we concluded that:

* LLVM allocates DI nodes with its custom allocator. `libc::free()`won't work. I didn't see any `*Dispose*` function for single metadata nodes in LLVM.
* The old elements might actually still be members of the DIScope or other metadata nodes, the "always free old" approach might not be a correct one.
* It's not that urgent to fix it here. We do tiny fixups and bpf-linker is using the most of memory for linking anyways.

That said, I'm happy to dig deeper and figure out if there is a sane way to free elements with the LLVM allocator. But maybe in a separate PR.
</blockquote></details>

Are you sure the elements aren't reference counted? I think they might be, and we need not do anything.


<!-- Sent from Reviewable.io -->

2023-11-27 23:48 UTC, vadorovsky commented
*[`src/llvm/di.rs` line 648 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/151#gh-1401354824:-NkI9WslBIO3fFIRCWta:b-ptjxgu) ([raw file](https://github.com/aya-rs/bpf-linker/blob/eb86a21f3dfd9ef9df0ab222ad7296a7bc1c7a8d/src/llvm/di.rs#L648)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Are you sure the elements aren't reference counted? I think they might be, and we need not do anything.
</blockquote></details>

OK, it is actually being handled gracefully in LLVM. I must've been blind before.

https://github.com/llvm/llvm-project/blob/be1e8a659df5003fa74e1f55c40acf3667f3cdb9/llvm/lib/IR/Core.cpp#L1339
https://github.com/llvm/llvm-project/blob/be1e8a659df5003fa74e1f55c40acf3667f3cdb9/llvm/lib/IR/Metadata.cpp#L1039
https://github.com/llvm/llvm-project/blob/be1e8a659df5003fa74e1f55c40acf3667f3cdb9/llvm/lib/IR/Metadata.cpp#L869-L917

Let me just remove this comment.


<!-- Sent from Reviewable.io -->

2023-11-27 23:58 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/151)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`src/llvm/di.rs` line 576 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/151#-NkBzgby4mIPtNg_Zlgv:-NkIAm-I5NNtKykVToF_:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/eb86a21f3dfd9ef9df0ab222ad7296a7bc1c7a8d/src/llvm/di.rs#L576)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

It should just be "another"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-28 06:17 UTC, alessandrod approved these changes

2023-11-28 08:20 UTC, merged