chore: Update to LLVM 19
aya-rs/bpf-linker pull request #214
Opened 2024-08-02 08:23 UTC by vadorovsky

Latest Rust nightly switched to LLVM 19, so we need to update in order to support rustc-llvm-proxy.

2024-08-02 12:27 UTC, tamird commented on .github/workflows/ci.yml
>            # tests/btf/assembly/anon_struct_c.rs to fail to link.
this is the reason CI is failing - we aren't on latest nightly here.

2024-08-10 15:28 UTC, tamird requested changes
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 4 unresolved discussions (waiting on @vadorovsky)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtmUODTPKQwWbqu2O):*
please include rationale
___
*[`Cargo.lock` line 84 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wsudw-Z8fShTbNQVt:-O3wsudw-Z8fShTbNQVu:bxrcjqq) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/Cargo.lock#L84)):*
> ```TOML
>  "libc",
>  "libloading",
>  "llvm-sys 180.0.0",
> ```

we now have two versions of llvm-sys, is that what we want?
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtL2x8XJZE2kz_Nej:-O3wtL2x8XJZE2kz_Nek:bb7r2f0) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L121)):*
> ```YAML
> 
>           sudo apt update
>           sudo apt -y install llvm-${{ matrix.llvm }}-dev libpolly-${{ matrix.llvm }}-dev
> ```

why?
___
*[`.github/workflows/ci.yml` line 153 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtR-p-woavEoa-Air:-O3wtR-p-woavEoa-Ais:b-kfj0ix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L153)):*
> ```YAML
>       - name: Check
>         if: matrix.llvm == 'source'
>         run: cargo hack check --feature-powerset --features llvm-sys/force-dynamic
> ```

just wondering: do we *need* to force it at all? can we just let it pick? the LLVM we build from source is going to be dynamic-only and we're already putting it at the front of the PATH.


<!-- Sent from Reviewable.io -->

2024-08-10 17:39 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 4 unresolved discussions (waiting on @tamird)

___
*[`Cargo.lock` line 84 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wsudw-Z8fShTbNQVt:-O3xKrbz3etSGgmNiHtE:b-tdlu7k) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/Cargo.lock#L84)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

we now have two versions of llvm-sys, is that what we want?
</blockquote></details>

sheesh, no, good catch
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtL2x8XJZE2kz_Nej:-O3xKWZpBZSQ3NLxEx-L:b1opo6e) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Because otherwise, llvm-sys fails to build with this error:

https://github.com/aya-rs/bpf-linker/actions/runs/10328832485/job/28595877283#step:17:20

```
     Compiling llvm-sys v191.0.0-rc1
     Compiling bpf-linker v0.9.12 (/home/runner/work/bpf-linker/bpf-linker)
  error: could not find native static library `Polly`, perhaps an -L flag is missing?
  
  error: could not compile `llvm-sys` (lib) due to 1 previous error
  warning: build failed, waiting for other jobs to finish...
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo build --manifest-path Cargo.toml --no-default-features` (exit status: 101)
```

I know that pulling libpolly is wasteful, but to not pull it, we would need to make build.rs in llvm-sys smarter. Currently, it just relies on the output of`llvm-config --system-libs`:

https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/build.rs?ref_type=heads#L297

Perhaps that needs a proper fix in llvm-config itself, I need to dig in more.
___
*[`.github/workflows/ci.yml` line 153 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtR-p-woavEoa-Air:-O3xLD5KEihQeYMsFWzo:b-mwxsrz) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

just wondering: do we *need* to force it at all? can we just let it pick? the LLVM we build from source is going to be dynamic-only and we're already putting it at the front of the PATH.
</blockquote></details>

Let me try.


<!-- Sent from Reviewable.io -->

2024-08-12 12:06 UTC, tamird requested changes
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 4 unresolved discussions (waiting on @vadorovsky)

___
*[`-- commits` line 8 at r4](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O45TRcGBXKORZdkc0HU):*
Needs an update
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtL2x8XJZE2kz_Nej:-O45TW4e2f16zoZgXLP2:b28qgn9) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L121)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Because otherwise, llvm-sys fails to build with this error:

https://github.com/aya-rs/bpf-linker/actions/runs/10328832485/job/28595877283#step:17:20

```
     Compiling llvm-sys v191.0.0-rc1
     Compiling bpf-linker v0.9.12 (/home/runner/work/bpf-linker/bpf-linker)
  error: could not find native static library `Polly`, perhaps an -L flag is missing?
  
  error: could not compile `llvm-sys` (lib) due to 1 previous error
  warning: build failed, waiting for other jobs to finish...
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo build --manifest-path Cargo.toml --no-default-features` (exit status: 101)
```

I know that pulling libpolly is wasteful, but to not pull it, we would need to make build.rs in llvm-sys smarter. Currently, it just relies on the output of`llvm-config --system-libs`:

https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/build.rs?ref_type=heads#L297

Perhaps that needs a proper fix in llvm-config itself, I need to dig in more.
</blockquote></details>

Include in commit message and maybe add a to-do?
___
*[`.github/workflows/ci.yml` line 153 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtR-p-woavEoa-Air:-O45TZTh5CzdI-Rfb8tr:b-q8osuc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L153)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Let me try.
</blockquote></details>

Needs an update in the commit message


<!-- Sent from Reviewable.io -->

2024-08-12 13:31 UTC, OmriSteiner commented
I was able to build my project with an update Rust nightly using this branch.

2024-08-12 15:35 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 4 unresolved discussions (waiting on @tamird)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtmUODTPKQwWbqu2O):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

please include rationale
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r4](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O45TRcGBXKORZdkc0HU):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Needs an update
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtL2x8XJZE2kz_Nej:-O46DfNv0j0ucJoPMkth:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Include in commit message and maybe add a to-do?
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 153 at r1](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O3wtR-p-woavEoa-Air:-O46Deq3A_Izx_ndlqip:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/b6a291c182a2ea8348f27aa05e25ce33ff829576/.github/workflows/ci.yml#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Needs an update in the commit message
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-12 15:53 UTC, tamird requested changes
> Reviewed 3 of 3 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 2 unresolved discussions (waiting on @vadorovsky)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46H6cDEeR66ls7EQc2):*
usage (typo)
___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O46HXcrDpiUyynee5h4:b-alx0et) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
> ```YAML
>           sudo apt update
>           # TODO(vadorovsky): Remove the requirement of libpolly. It's being
>           # unnecessarily required by build.rs of llvm-sys, which does so based
> ```

is it really required by build.rs? i see no mention of libpolly in https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/build.rs - what am I missing?


<!-- Sent from Reviewable.io -->

2024-08-12 17:31 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @vadorovsky)

___
*[`-- commits` line 37 at r11](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46dApFEfmM2JIE2mTs):*
just squash this into the first commit?


<!-- Sent from Reviewable.io -->

2024-08-12 18:33 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O46jxKf6FpG0nvN0tK6:b-c6ng7p) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it really required by build.rs? i see no mention of libpolly in https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/build.rs - what am I missing?
</blockquote></details>

build.rs is calling `llvm-config --libnames --link-[dynamic|static]` here:

https://gitlab.com/taricorp/llvm-sys.rs/-/blob/48a97a9b4a33a25513e875ac0899fa0f8403418f/build.rs#L478

which returns:

```
llvm-config --libnames --link-static
libLLVMWindowsManifest.a libLLVMXRay.a libLLVMLibDriver.a libLLVMDlltoolDriver.a libLLVMTextAPIBinaryReader.a libLLVMCoverage.a libLLVMLineEditor.a libLLVMSandboxIR.a libLLVMXtensaDisassembler.a libLLVMXtensaAsmParser.a libLLVMXtensaCodeGen.a libLLVMXtensaDesc.a libLLVMXtensaInfo.a libLLVMM68kDisassembler.a libLLVMM68kAsmParser.a libLLVMM68kCode
Gen.a libLLVMM68kDesc.a libLLVMM68kInfo.a libLLVMXCoreDisassembler.a libLLVMXCoreCodeGen.a libLLVMXCoreDesc.a libLLVMXCoreInfo.a libLLVMX86TargetMCA.a libLLVMX86Disassembler.a libLLVMX86AsmParser.a libLLVMX86CodeGen.a libLLVMX86Desc.a libLLVMX86Info.a libLLVMWebAssemblyDisassembler.a libLLVMWebAssemblyAsmParser.a libLLVMWebAssemblyCodeGen.a libLLVMWebAssemblyUtils.a libLLVMWebAssemblyDesc.a libLLVMWebAssemblyInfo.a libLLVMVEDisassembler.a libLLVMVEAsmParser.a libLLVMVECodeGen.a libLLVMVEDesc.a libLLVMVEInfo.a libLLVMSystemZDisassembler.a libLLVMSystemZAsmParser.a libLLVMSystemZCodeGen.a libLLVMSystemZDesc.a libLLVMSystemZInfo.a libLLVMSparcDisassembler.a libLLVMSparcAsmParser.a libLLVMSparcCodeGen.a libLLVMSparcDesc.a libLLVMSparcInfo.a libLLVMRISCVTargetMCA.a libLLVMRISCVDisassembler.a libLLVMRISCVAsmParser.a libLLVMRISCVCodeGen.a libLLVMRISCVDesc.a libLLVMRISCVInfo.a libLLVMPowerPCDisassembler.a libLLVMPowerPCAsmParser.a libLLVMPowerPCCodeGen.a libLLVMPowerPCDesc.a libLLVMPowerPCInfo.a libLLVMNVPTXCodeGen.a libLLVMNVPTXDesc.a libLLVMNVPTXInfo.a libLLVMMSP430Disassembler.a libLLVMMSP430AsmParser.a libLLVMMSP430CodeGen.a libLLVMMSP430Desc.a libLLVMMSP430Info.a libLLVMMipsDisassembler.a libLLVMMipsAsmParser.a libLLVMMipsCodeGen.a libLLVMMipsDesc.a libLLVMMipsInfo.a libLLVMLoongArchDisassembler.a libLLVMLoongArchAsmParser.a libLLVMLoongArchCodeGen.a libLLVMLoongArchDesc.a libLLVMLoongArchInfo.a libLLVMLanaiDisassembler.a libLLVMLanaiCodeGen.a libLLVMLanaiAsmParser.a libLLVMLanaiDesc.a libLLVMLanaiInfo.a libLLVMHexagonDisassembler.a libLLVMHexagonCodeGen.a libLLVMHexagonAsmParser.a libLLVMHexagonDesc.a libLLVMHexagonInfo.a libLLVMBPFDisassembler.a libLLVMBPFAsmParser.a libLLVMBPFCodeGen.a libLLVMBPFDesc.a libLLVMBPFInfo.a libLLVMAVRDisassembler.a libLLVMAVRAsmParser.a libLLVMAVRCodeGen.a libLLVMAVRDesc.a libLLVMAVRInfo.a libLLVMARMDisassembler.a libLLVMARMAsmParser.a libLLVMARMCodeGen.a libLLVMARMDesc.a libLLVMARMUtils.a libLLVMARMInfo.a libLLVMAMDGPUTargetMCA.a libLLVMAMDGPUDisassembler.a libLLVMAMDGPUAsmParser.a libLLVMAMDGPUCodeGen.a libLLVMAMDGPUDesc.a libLLVMAMDGPUUtils.a libLLVMAMDGPUInfo.a libLLVMAArch64Disassembler.a libLLVMAArch64AsmParser.a libLLVMAArch64CodeGen.a libLLVMAArch64Desc.a libLLVMAArch64Utils.a libLLVMAArch64Info.a libLLVMPerfJITEvents.a libLLVMOrcDebugging.a libLLVMOrcJIT.a libLLVMWindowsDriver.a libLLVMMCJIT.a libLLVMJITLink.a libLLVMInterpreter.a libLLVMExecutionEngine.a libLLVMRuntimeDyld.a libLLVMOrcTargetProcess.a libLLVMOrcShared.a libLLVMDWP.a libLLVMDebugInfoLogicalView.a libLLVMDebugInfoGSYM.a libLLVMOption.a libLLVMObjectYAML.a libLLVMObjCopy.a libLLVMMCA.a libLLVMMCDisassembler.a libLLVMLTO.a libLLVMFrontendOpenACC.a libLLVMFrontendHLSL.a libLLVMFrontendDriver.a libLLVMExtensions.a libPolly.a libPollyISL.a libLLVMPasses.a libLLVMHipStdPar.a libLLVMCoroutines.a libLLVMCFGuard.a libLLVMipo.a libLLVMInstrumentation.a libLLVMVectorize.a libLLVMLinker.a libLLVMFrontendOpenMP.a libLLVMFrontendOffloading.a libLLVMDWARFLinkerParallel.a libLLVMDWARFLinkerClassic.a libLLVMDWARFLinker.a libLLVMCodeGenData.a libLLVMGlobalISel.a libLLVMMIRParser.a libLLVMAsmPrinter.a libLLVMSelectionDAG.a libLLVMCodeGen.a libLLVMTarget.a libLLVMObjCARCOpts.a libLLVMCodeGenTypes.a libLLVMIRPrinter.a libLLVMInterfaceStub.a libLLVMFileCheck.a libLLVMFuzzMutate.a libLLVMScalarOpts.a libLLVMInstCombine.a libLLVMAggressiveInstCombine.a libLLVMTransformUtils.a libLLVMBitWriter.a libLLVMAnalysis.a libLLVMProfileData.a libLLVMSymbolize.a libLLVMDebugInfoBTF.a libLLVMDebugInfoPDB.a libLLVMDebugInfoMSF.a libLLVMDebugInfoDWARF.a libLLVMObject.a libLLVMTextAPI.a libLLVMMCParser.a libLLVMIRReader.a libLLVMAsmParser.a libLLVMMC.a libLLVMDebugInfoCodeView.a libLLVMBitReader.a libLLVMFuzzerCLI.a libLLVMCore.a libLLVMRemarks.a libLLVMBitstreamReader.a libLLVMBinaryFormat.a libLLVMTargetParser.a libLLVMTableGen.a libLLVMSupport.a libLLVMDemangle.a
```

You can see `libPolly.a` and `libPollyISL.a` being mentioned there. And then build.rs just blindly follows and tries to link all these libs.


<!-- Sent from Reviewable.io -->

2024-08-12 18:35 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O46rfCi2ikoaYqSCXAl:b-lmcvu3) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

build.rs is calling `llvm-config --libnames --link-[dynamic|static]` here:

https://gitlab.com/taricorp/llvm-sys.rs/-/blob/48a97a9b4a33a25513e875ac0899fa0f8403418f/build.rs#L478

which returns:

```
llvm-config --libnames --link-static
libLLVMWindowsManifest.a libLLVMXRay.a libLLVMLibDriver.a libLLVMDlltoolDriver.a libLLVMTextAPIBinaryReader.a libLLVMCoverage.a libLLVMLineEditor.a libLLVMSandboxIR.a libLLVMXtensaDisassembler.a libLLVMXtensaAsmParser.a libLLVMXtensaCodeGen.a libLLVMXtensaDesc.a libLLVMXtensaInfo.a libLLVMM68kDisassembler.a libLLVMM68kAsmParser.a libLLVMM68kCode
Gen.a libLLVMM68kDesc.a libLLVMM68kInfo.a libLLVMXCoreDisassembler.a libLLVMXCoreCodeGen.a libLLVMXCoreDesc.a libLLVMXCoreInfo.a libLLVMX86TargetMCA.a libLLVMX86Disassembler.a libLLVMX86AsmParser.a libLLVMX86CodeGen.a libLLVMX86Desc.a libLLVMX86Info.a libLLVMWebAssemblyDisassembler.a libLLVMWebAssemblyAsmParser.a libLLVMWebAssemblyCodeGen.a libLLVMWebAssemblyUtils.a libLLVMWebAssemblyDesc.a libLLVMWebAssemblyInfo.a libLLVMVEDisassembler.a libLLVMVEAsmParser.a libLLVMVECodeGen.a libLLVMVEDesc.a libLLVMVEInfo.a libLLVMSystemZDisassembler.a libLLVMSystemZAsmParser.a libLLVMSystemZCodeGen.a libLLVMSystemZDesc.a libLLVMSystemZInfo.a libLLVMSparcDisassembler.a libLLVMSparcAsmParser.a libLLVMSparcCodeGen.a libLLVMSparcDesc.a libLLVMSparcInfo.a libLLVMRISCVTargetMCA.a libLLVMRISCVDisassembler.a libLLVMRISCVAsmParser.a libLLVMRISCVCodeGen.a libLLVMRISCVDesc.a libLLVMRISCVInfo.a libLLVMPowerPCDisassembler.a libLLVMPowerPCAsmParser.a libLLVMPowerPCCodeGen.a libLLVMPowerPCDesc.a libLLVMPowerPCInfo.a libLLVMNVPTXCodeGen.a libLLVMNVPTXDesc.a libLLVMNVPTXInfo.a libLLVMMSP430Disassembler.a libLLVMMSP430AsmParser.a libLLVMMSP430CodeGen.a libLLVMMSP430Desc.a libLLVMMSP430Info.a libLLVMMipsDisassembler.a libLLVMMipsAsmParser.a libLLVMMipsCodeGen.a libLLVMMipsDesc.a libLLVMMipsInfo.a libLLVMLoongArchDisassembler.a libLLVMLoongArchAsmParser.a libLLVMLoongArchCodeGen.a libLLVMLoongArchDesc.a libLLVMLoongArchInfo.a libLLVMLanaiDisassembler.a libLLVMLanaiCodeGen.a libLLVMLanaiAsmParser.a libLLVMLanaiDesc.a libLLVMLanaiInfo.a libLLVMHexagonDisassembler.a libLLVMHexagonCodeGen.a libLLVMHexagonAsmParser.a libLLVMHexagonDesc.a libLLVMHexagonInfo.a libLLVMBPFDisassembler.a libLLVMBPFAsmParser.a libLLVMBPFCodeGen.a libLLVMBPFDesc.a libLLVMBPFInfo.a libLLVMAVRDisassembler.a libLLVMAVRAsmParser.a libLLVMAVRCodeGen.a libLLVMAVRDesc.a libLLVMAVRInfo.a libLLVMARMDisassembler.a libLLVMARMAsmParser.a libLLVMARMCodeGen.a libLLVMARMDesc.a libLLVMARMUtils.a libLLVMARMInfo.a libLLVMAMDGPUTargetMCA.a libLLVMAMDGPUDisassembler.a libLLVMAMDGPUAsmParser.a libLLVMAMDGPUCodeGen.a libLLVMAMDGPUDesc.a libLLVMAMDGPUUtils.a libLLVMAMDGPUInfo.a libLLVMAArch64Disassembler.a libLLVMAArch64AsmParser.a libLLVMAArch64CodeGen.a libLLVMAArch64Desc.a libLLVMAArch64Utils.a libLLVMAArch64Info.a libLLVMPerfJITEvents.a libLLVMOrcDebugging.a libLLVMOrcJIT.a libLLVMWindowsDriver.a libLLVMMCJIT.a libLLVMJITLink.a libLLVMInterpreter.a libLLVMExecutionEngine.a libLLVMRuntimeDyld.a libLLVMOrcTargetProcess.a libLLVMOrcShared.a libLLVMDWP.a libLLVMDebugInfoLogicalView.a libLLVMDebugInfoGSYM.a libLLVMOption.a libLLVMObjectYAML.a libLLVMObjCopy.a libLLVMMCA.a libLLVMMCDisassembler.a libLLVMLTO.a libLLVMFrontendOpenACC.a libLLVMFrontendHLSL.a libLLVMFrontendDriver.a libLLVMExtensions.a libPolly.a libPollyISL.a libLLVMPasses.a libLLVMHipStdPar.a libLLVMCoroutines.a libLLVMCFGuard.a libLLVMipo.a libLLVMInstrumentation.a libLLVMVectorize.a libLLVMLinker.a libLLVMFrontendOpenMP.a libLLVMFrontendOffloading.a libLLVMDWARFLinkerParallel.a libLLVMDWARFLinkerClassic.a libLLVMDWARFLinker.a libLLVMCodeGenData.a libLLVMGlobalISel.a libLLVMMIRParser.a libLLVMAsmPrinter.a libLLVMSelectionDAG.a libLLVMCodeGen.a libLLVMTarget.a libLLVMObjCARCOpts.a libLLVMCodeGenTypes.a libLLVMIRPrinter.a libLLVMInterfaceStub.a libLLVMFileCheck.a libLLVMFuzzMutate.a libLLVMScalarOpts.a libLLVMInstCombine.a libLLVMAggressiveInstCombine.a libLLVMTransformUtils.a libLLVMBitWriter.a libLLVMAnalysis.a libLLVMProfileData.a libLLVMSymbolize.a libLLVMDebugInfoBTF.a libLLVMDebugInfoPDB.a libLLVMDebugInfoMSF.a libLLVMDebugInfoDWARF.a libLLVMObject.a libLLVMTextAPI.a libLLVMMCParser.a libLLVMIRReader.a libLLVMAsmParser.a libLLVMMC.a libLLVMDebugInfoCodeView.a libLLVMBitReader.a libLLVMFuzzerCLI.a libLLVMCore.a libLLVMRemarks.a libLLVMBitstreamReader.a libLLVMBinaryFormat.a libLLVMTargetParser.a libLLVMTableGen.a libLLVMSupport.a libLLVMDemangle.a
```

You can see `libPolly.a` and `libPollyISL.a` being mentioned there. And then build.rs just blindly follows and tries to link all these libs.
</blockquote></details>

You can do the following to reproduce:

```
podman run --rm -it docker.io/ubuntu:22.04
apt update
apt install lsb-release wget software-properties-common gnupg
./llvm.sh 19 all
/usr/lib/llvm-19/bin/llvm-config --libnames --link-static
```


<!-- Sent from Reviewable.io -->

2024-08-12 18:38 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O46sM_V0rgtIJIK5l0l:b-y64s2j) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

You can do the following to reproduce:

```
podman run --rm -it docker.io/ubuntu:22.04
apt update
apt install lsb-release wget software-properties-common gnupg
./llvm.sh 19 all
/usr/lib/llvm-19/bin/llvm-config --libnames --link-static
```
</blockquote></details>

uhh, sorry, missed few commands

```
podman run --rm -it docker.io/ubuntu:22.04
apt update
apt install lsb-release wget software-properties-common gnupg
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh 19 all
/usr/lib/llvm-19/bin/llvm-config --libnames --link-static
```


<!-- Sent from Reviewable.io -->

2024-08-12 19:11 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @vadorovsky)

___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O46zvqO7tR6WBkge-8S:bx5iogq) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

uhh, sorry, missed few commands

```
podman run --rm -it docker.io/ubuntu:22.04
apt update
apt install lsb-release wget software-properties-common gnupg
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh 19 all
/usr/lib/llvm-19/bin/llvm-config --libnames --link-static
```
</blockquote></details>

Got it. It's worthwhile to capture some of this here - the current phrasing suggests that build.rs is directly referencing libpolly.

FWIW this definitely looks like a packaging bug - it looks as if LLVM was built with libpolly but libpolly wasn't included in the package.


<!-- Sent from Reviewable.io -->

2024-08-12 20:17 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: all files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`.github/workflows/ci.yml` line 122 at r8](https://reviewable.io/reviews/aya-rs/bpf-linker/214#-O46HXcrDpiUyynee5h3:-O477YhD-fwYNYrKLkhM:b8du59j) ([raw file](https://github.com/aya-rs/bpf-linker/blob/05f578ea53ab148db31646eddaf9d7722758dff4/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Got it. It's worthwhile to capture some of this here - the current phrasing suggests that build.rs is directly referencing libpolly.

FWIW this definitely looks like a packaging bug - it looks as if LLVM was built with libpolly but libpolly wasn't included in the package.
</blockquote></details>

Yeah, it looks like apt.llvm.org folks are just building the whole monorepo at once with powerset of cmake options and then putting different libs and binaries to different deb packages.

I quickly checked on Fedora and Gentoo and the problem doesn't exist there, each package (llvm(-dev), compiler-rt, polly(-dev)) is being built separately, even though the sources are the same.

And here is a funny thing. I checked how is it in the LLVM tarball from Rust. The output is empty :skull: 

```
$ ./bin/llvm-config --libnames --link-static

$
```

But it's fine, we can just define appropriate `-L` flags in `RUSTFLAGS`. I think I even prefer it this way. :stuck_out_tongue: 

Pushed the change with more verbose comment and commit message.


<!-- Sent from Reviewable.io -->

2024-08-12 20:44 UTC, tamird approved these changes
> Reviewed 3 of 3 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2024-08-13 06:49 UTC, merged