Provide `LLVMTypeWrapper` trait
aya-rs/bpf-linker pull request #223
Opened 2024-09-09 09:10 UTC by vadorovsky

Instead of keeping raw pointer fields (of types like `LLVMValueRef`, `LLVMMetadataRef`) public and defining constructors with different names, provide the `LLVMTypeWrapper` trait with `from_ptr()` `as_ptr()` method for all of them.

This will allow to convert all safe wrappers from and to raw pointers with one method, which is going to be helpful for building macros for them.

---

Depends on #222

2024-09-09 14:29 UTC, tamird requested changes
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 11 unresolved discussions (waiting on @vadorovsky)

___
*[`src/llvm/types/di.rs` line 54 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MACo63ar6Y243gCDO:-O6MACo63ar6Y243gCDP:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L54)):*
> ```XML
>     type Target = LLVMMetadataRef;
> 
>     /// Constructs a new [`DIFile`] from the given `metadata`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/di.rs` line 131 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAFAW2-TJx7tXyfSq:-O6MAFAW2-TJx7tXyfSr:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L131)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`DIType`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/di.rs` line 190 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAHgD1oEpWkJmTYPO:-O6MAHgD1oEpWkJmTYPP:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L190)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`DIDerivedType`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/di.rs` line 259 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAIvVAAAzrWc_cB9w:-O6MAIvVAAAzrWc_cB9x:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L259)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`DICompositeType`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/di.rs` line 369 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAJWV07NisR-8HUiJ:-O6MAJWV07NisR-8HUiK:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L369)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`DISubprogram`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/ir.rs` line 214 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAn68E31417_I3P79:-O6MAn68E31417_I3P7A:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L214)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`MDNode`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/ir.rs` line 221 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAcG39SWiUICGE_qp:-O6MAcG39SWiUICGE_qq:b5f0tav) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L221)):*
> ```XML
>     /// instance of [LLVM `MDNode`](https://llvm.org/doxygen/classllvm_1_1MDNode.html).
>     /// It's the caller's responsibility to ensure this invariant, as this
>     /// method doesn't perform any valiation checks.
> ```

"valiation" typo throughout
___
*[`src/llvm/types/ir.rs` line 243 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAyVZELkZep6v98-4:-O6MAyVZELkZep6v98-5:b-jj5pvn) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L243)):*
> ```XML
>     /// It's the caller's responsibility to ensure this invariant, as this
>     /// method doesn't perform any validation checks.
>     pub(crate) unsafe fn from_metadata_ref(
> ```

could we just inline this method?
___
*[`src/llvm/types/ir.rs` line 251 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAZj81EnzMTq9Ytlt:-O6MAZj81EnzMTq9Ytlu:b-hasvcj) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L251)):*
> ```XML
> 
>     /// Constructs an empty metadata node.
>     /// Constructs a new [`MDNode`] from the given `value`.
> ```

detritus
___
*[`src/llvm/types/ir.rs` line 333 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAgDk0t4l3GJFbSip:-O6MAgDk0t4l3GJFbSiq:b-74dbwc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L333)):*
> ```XML
>     type Target = LLVMValueRef;
> 
>     /// Constructs a new [`Function`] from the given `value`.
> ```

looks like this comment should go on the trait now.
___
*[`src/llvm/types/mod.rs` line 7 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6M9wCqEFRJj71puhcB:-O6M9wCqEFRJj71puhcC:b-bekbs3) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/mod.rs#L7)):*
> ```XML
>     type Target: ?Sized;
> 
>     unsafe fn from_ptr(ptr: Self::Target) -> Self;
> ```

why is it unsafe?


<!-- Sent from Reviewable.io -->

2024-09-09 20:29 UTC, vadorovsky commented
*[`src/llvm/types/mod.rs` line 7 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6M9wCqEFRJj71puhcB:-O6NS8dxCna4D-9hYn9x:bnidsxj) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/mod.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why is it unsafe?
</blockquote></details>

The most of pointer types coming from LLVM-C API (through llvm-sys) are more vague than the C++ ones.

There is `LLVMValueRef` which can be pretty much anything - `Value`, `Instruction`, `GlobalVariable` or any of dozens of classes inheriting from `Value`. Therefore constructing a wrapper corresponding to a C++ type (e.g. `Instruction`) from `LLVMValueRef` is unsafe, unless you perform a direct check.

But good that you asked. I didn't think about it before, but there are functions like `IsAMDNode` or `IsAInstruction` for performing such checks. Let me check if they cover **all** the types. If yes, I could make it method safe and just make sure we have checks everywhere. If no, I would either insist on keeping this unsafe or provide a separate method/trait for types for which the check functions exist.


<!-- Sent from Reviewable.io -->

2024-11-27 13:54 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/types/di.rs` line 54 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MACo63ar6Y243gCDO:-OChrTthDmPWBYCS3BDA:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L54)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/di.rs` line 131 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAFAW2-TJx7tXyfSq:-OChrU9gApVJHCwfNjHV:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L131)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/di.rs` line 190 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAHgD1oEpWkJmTYPO:-OChrUlQ8G1xUfQv9Ptq:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L190)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/di.rs` line 259 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAIvVAAAzrWc_cB9w:-OChrV8U-xA934rzCq84:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L259)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/di.rs` line 369 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAJWV07NisR-8HUiJ:-OChrVXB8E_qZY0bDeTW:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/di.rs#L369)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/ir.rs` line 214 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAn68E31417_I3P79:-OChrWI54NrM3rFYZsye:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L214)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/ir.rs` line 221 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAcG39SWiUICGE_qp:-OChrWeZ82ei058cP6WZ:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L221)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"valiation" typo throughout
</blockquote></details>

Done.
___
*[`src/llvm/types/ir.rs` line 243 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAyVZELkZep6v98-4:-OChtgiE3MLnJkMacZHL:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L243)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

could we just inline this method?
</blockquote></details>

Done.
___
*[`src/llvm/types/ir.rs` line 251 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAZj81EnzMTq9Ytlt:-OChth-D27X5TxZIn4n8:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L251)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

detritus
</blockquote></details>

Done.
___
*[`src/llvm/types/ir.rs` line 333 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6MAgDk0t4l3GJFbSip:-OChrbetCBqK3IESguFA:b-896fix) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/ir.rs#L333)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like this comment should go on the trait now.
</blockquote></details>

Done.
___
*[`src/llvm/types/mod.rs` line 7 at r2](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-O6M9wCqEFRJj71puhcB:-OChrcc509uGyOUn49qA:bt130in) ([raw file](https://github.com/aya-rs/bpf-linker/blob/dbf6033f12073bea4885e97b753ecb7c55e5f8f9/src/llvm/types/mod.rs#L7)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

The most of pointer types coming from LLVM-C API (through llvm-sys) are more vague than the C++ ones.

There is `LLVMValueRef` which can be pretty much anything - `Value`, `Instruction`, `GlobalVariable` or any of dozens of classes inheriting from `Value`. Therefore constructing a wrapper corresponding to a C++ type (e.g. `Instruction`) from `LLVMValueRef` is unsafe, unless you perform a direct check.

But good that you asked. I didn't think about it before, but there are functions like `IsAMDNode` or `IsAInstruction` for performing such checks. Let me check if they cover **all** the types. If yes, I could make it method safe and just make sure we have checks everywhere. If no, I would either insist on keeping this unsafe or provide a separate method/trait for types for which the check functions exist.
</blockquote></details>

Done, I made the method safe and I added checks in each implementation.


<!-- Sent from Reviewable.io -->

2024-11-27 15:12 UTC, tamird requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 12 unresolved discussions (waiting on @vadorovsky)

___
*[`src/llvm/mod.rs` line 3 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9PlhEJ2KhLkqdkVn:-OCi9PlhEJ2KhLkqdkVo:b-2dth75) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/mod.rs#L3)):*
> ```XML
> mod di;
> mod iter;
> pub mod types;
> ```

what does it mean for this to be pub?
___
*[`src/llvm/types/mod.rs` line 9 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi6xrd85-wkwmwDTcS:-OCi6xrd85-wkwmwDTcT:b-fam1) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L9)):*
> ```XML
> pub enum LLVMTypeError {
>     #[error("invalid pointer type, expected {0}")]
>     InvalidPointerType(&'static str),
> ```

nit: maybe we can use TypeId here? https://doc.rust-lang.org/stable/std/any/struct.TypeId.html

EDIT: seems like no because there are sometimes multiple admissible types, but i think we do want the unexpected type to be shown
___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCi667e8VFgxFMFkgFE:b-wjebzr) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
> ```XML
>     InvalidPointerType(&'static str),
>     #[error("null pointer")]
>     NullPointer,
> ```

it would be neat to lift the null check to the caller using NonNull, but to do it would be a bit convoluted, you'd need something like

```rust
trait Pointer {
  type PointedTo;
}

impl<T> Pointer for *mut T {
  type PointedTo = T;
}
```

and then

```rust
trait LLVMTypeWrapper {
  type Target: Pointer;

  fn from_ptr(ptr: std::ptr::NonNull<Self::Target::PointedTo>) -> ...
}
```

unclear if it's worth it, but i'll let you decide
___
*[`src/llvm/types/mod.rs` line 15 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi627TA9azWI5IqmW5:-OCi627TA9azWI5IqmW6:b-fv1vpg) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L15)):*
> ```XML
> 
> pub trait LLVMTypeWrapper {
>     type Target: ?Sized;
> ```

how can target be unsized? aren't we always returning a pointer which is word-sized?
___
*[`src/llvm/types/mod.rs` line 20 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi4NB7BSggagrna8JI:-OCi4NB7BSggagrna8JJ:b-uriw7d) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L20)):*
> ```XML
>     fn from_ptr(ptr: Self::Target) -> Result<Self, LLVMTypeError>
>     where
>         Self: Sized;
> ```

is this bound required? I'm surprised
___
*[`src/linker.rs` line 81 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi3uf33vxUI2JdBdVb:-OCi3uf33vxUI2JdBdVc:bqbv6fm) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/linker.rs#L81)):*
> ```XML
>     MissingBitcodeSection(PathBuf),
> 
>     /// Interaction with an LLVM type failed.
> ```

"interaction"?
___
*[`src/llvm/types/di.rs` line 158 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9bTy9dFe605YOdkO:-OCi9bTy9dFe605YOdkP:b-gmjnlj) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/di.rs#L158)):*
> ```XML
>                 _marker: PhantomData,
>             }),
>             _ => Err(LLVMTypeError::InvalidPointerType("DIType")),
> ```

seems like it would be nice to emit the unexpected type
___
*[`src/llvm/types/di.rs` line 236 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9maP1I7T1cEyPAbb:-OCi9maP1I7T1cEyPAbc:byyics6) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/di.rs#L236)):*
> ```XML
>         unsafe {
>             let value = LLVMGetOperand(self.value_ref, DIDerivedTypeOperand::BaseType as u32);
>             // PANICS: We are sure that the pointer type is correct. There is
> ```

these comments can easily be `expect`s, or perhaps a helper function with a descriptive name so we don't need 6 copies of this comment.
___
*[`src/llvm/types/ir.rs` line 86 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCiAGzoC-hq_JhJQiPF:-OCiAGzoC-hq_JhJQiPG:boydgkp) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L86)):*
> ```XML
>         if unsafe { !LLVMIsAMDNode(value_ref).is_null() } {
>             let mdnode = MDNode::from_ptr(value_ref)?;
>             return Ok(Value::MDNode(mdnode));
> ```

super nit: drop all the `return`s and use `else` for `Other`
___
*[`src/llvm/types/ir.rs` line 240 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCiA1cX9HulhNCmgA1J:-OCiA1cX9HulhNCmgA1K:bi1y70q) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L240)):*
> ```XML
>     ) -> Result<Self, LLVMTypeError> {
>         let value_ref = unsafe { LLVMMetadataAsValue(context, metadata) };
>         MDNode::from_ptr(value_ref)
> ```

isn't this the kind of place where you have chosen to panic?
___
*[`src/llvm/types/ir.rs` line 359 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi83bm-j6tzEd2zTAT:-OCi83bm-j6tzEd2zTAU:b-b5acww) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L359)):*
> ```XML
>         let subprogram = unsafe { LLVMGetSubprogram(self.value_ref) };
>         NonNull::new(subprogram).map(|_| unsafe {
>             // PANICS: We are sure that the pointer type is correct. There is
> ```

this API is weird, we're treating nullptr as None here while it's normally an error. This again goes to pushing null checks to the caller.
___
*[`src/llvm/di.rs` line 340 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9FAd4tqfJ7yakN6d:-OCi9FAd4tqfJ7yakN6e:b4y406x) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/di.rs#L340)):*
> ```XML
> 
>         for function in self.module.functions_iter().map(Function::from_ptr) {
>             let mut function = function?;
> ```

instead of this, we should push the LLVMTypeWrapper::from_ptr call into the `llvm_iterator!` macro.


<!-- Sent from Reviewable.io -->

2024-11-27 18:08 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 12 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/mod.rs` line 3 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9PlhEJ2KhLkqdkVn:-OCihgov8-RhMSbN3YzZ:b3vnb34) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/mod.rs#L3)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what does it mean for this to be pub?
</blockquote></details>

I did that to be able to import `use crate::llvm::types::LLVMTypeError` outside of llvm module.
___
*[`src/llvm/types/ir.rs` line 240 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCiA1cX9HulhNCmgA1J:-OCiE6dY5sfIietRU3Gn:b2hfxnx) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L240)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

isn't this the kind of place where you have chosen to panic?
</blockquote></details>

Not really. This `from_metadata_ref` method takes any `LLVMMetadataRef` pointer and converts it into our `MDNode` wrapper. It can result in an error in case caller provides a null pointer or some other subtype of `Metadata` which is not `MDNode`.

I'm fine with panicking in situations when some method is creating an `LLVMValueRef` or `LLVMMetadataRef` internally (e.g. by getting an operand of the current item) and we are absolutely sure nothing can go wrong (unless LLVM itself has a major bug - let's say, getting operands doesn't work as expected or the type hierarchy is broken).
___
*[`src/llvm/types/ir.rs` line 359 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi83bm-j6tzEd2zTAT:-OCihvlJ9MbdWcSqOOTW:b-mpi3rv) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L359)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this API is weird, we're treating nullptr as None here while it's normally an error. This again goes to pushing null checks to the caller.
</blockquote></details>

In LLVM-C API, a null pointer might mean three things:

- the object you requested doesn't exist, but your request was still valid and that lack of existence is fine (the existence of the object is optional) - this is the case here
- the object doesn't exist and it's not fine, the lack of existence breaks the logic
- the caller screwed up and passed something invalid - that's the case in the other places where I'm returning `Result`

I think our Rust wrappers should differentiate between first case (where using `Option` is appropriate) and the latter cases.

In case of `LLVMGetSubprogram`, which ends up calling `Function::getSubprogram` from LLVM C++ API, having a `nullptr` result is valid, because this code:

https://github.com/llvm/llvm-project/blob/llvmorg-19.1.4/llvm/lib/IR/Metadata.cpp#L1831-L1833

uses `cast_or_null`. `cast_if_present` and `cast_or_null` mean "convert this type if not null, otherwise return null" and is generally used in places which return optional objects.
___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCimzj28hhJmatj3RVo:b-vzvabu) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it would be neat to lift the null check to the caller using NonNull, but to do it would be a bit convoluted, you'd need something like

```rust
trait Pointer {
  type PointedTo;
}

impl<T> Pointer for *mut T {
  type PointedTo = T;
}
```

and then

```rust
trait LLVMTypeWrapper {
  type Target: Pointer;

  fn from_ptr(ptr: std::ptr::NonNull<Self::Target::PointedTo>) -> ...
}
```

unclear if it's worth it, but i'll let you decide
</blockquote></details>

Let me try that, requiring `NonNull` sounds great from the point of view of handling null pointers correctly.

BTW, my long-term intention is to wrap absolutely every type and remove the direct `from_ptr` usage, especially in `src/linker/di.rs`.
___
*[`src/llvm/types/mod.rs` line 15 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi627TA9azWI5IqmW5:-OCinfRLD4VdIWG3-w6f:bqvhr85) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L15)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how can target be unsized? aren't we always returning a pointer which is word-sized?
</blockquote></details>

You're right, we should require `Sized` here.
___
*[`src/llvm/types/mod.rs` line 20 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi4NB7BSggagrna8JI:-OCinrSkE5lggOcmAsn3:be17egz) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this bound required? I'm surprised
</blockquote></details>

Yeah, removing that bound results in this error:

```
   Compiling bpf-linker v0.9.13 (/home/vadorovsky/src/bpf-linker)
error[E0277]: the size for values of type `Self` cannot be known at compilation time
   --> src/llvm/types/mod.rs:18:39
    |
18  |     fn from_ptr(ptr: Self::Target) -> Result<Self, LLVMTypeError>;
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
note: required by an implicit `Sized` bound in `Result`
   --> /home/vadorovsky/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/lib/rustlib/src/rust/library/core/src/result.rs:528:17
    |
528 | pub enum Result<T, E> {
    |                 ^ required by the implicit `Sized` requirement on this type parameter in `Result`
help: consider further restricting `Self`
    |
18  |     fn from_ptr(ptr: Self::Target) -> Result<Self, LLVMTypeError> where Self: Sized;
```


<!-- Sent from Reviewable.io -->

2024-11-27 18:10 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 12 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/types/ir.rs` line 359 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi83bm-j6tzEd2zTAT:-OCio3Ks4HaC0q9vbR3e:bk7h9bt) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L359)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

In LLVM-C API, a null pointer might mean three things:

- the object you requested doesn't exist, but your request was still valid and that lack of existence is fine (the existence of the object is optional) - this is the case here
- the object doesn't exist and it's not fine, the lack of existence breaks the logic
- the caller screwed up and passed something invalid - that's the case in the other places where I'm returning `Result`

I think our Rust wrappers should differentiate between first case (where using `Option` is appropriate) and the latter cases.

In case of `LLVMGetSubprogram`, which ends up calling `Function::getSubprogram` from LLVM C++ API, having a `nullptr` result is valid, because this code:

https://github.com/llvm/llvm-project/blob/llvmorg-19.1.4/llvm/lib/IR/Metadata.cpp#L1831-L1833

uses `cast_or_null`. `cast_if_present` and `cast_or_null` mean "convert this type if not null, otherwise return null" and is generally used in places which return optional objects.
</blockquote></details>

To put it in easier words - `LLVMGetSubprogram`/`Function::getSubprogram` tolerates the case when the given function has no subprogram.


<!-- Sent from Reviewable.io -->

2024-11-27 18:12 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 12 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/types/ir.rs` line 240 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCiA1cX9HulhNCmgA1J:-OCioWZS50kUEdcURs96:bz84ikh) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L240)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Not really. This `from_metadata_ref` method takes any `LLVMMetadataRef` pointer and converts it into our `MDNode` wrapper. It can result in an error in case caller provides a null pointer or some other subtype of `Metadata` which is not `MDNode`.

I'm fine with panicking in situations when some method is creating an `LLVMValueRef` or `LLVMMetadataRef` internally (e.g. by getting an operand of the current item) and we are absolutely sure nothing can go wrong (unless LLVM itself has a major bug - let's say, getting operands doesn't work as expected or the type hierarchy is broken).
</blockquote></details>

To put it in easier words:

- I'm panicking when I'm sure that caller's input can't result in getting a `nullptr`.
- I'm returning the error when there is no such guarantee.


<!-- Sent from Reviewable.io -->

2024-11-27 19:13 UTC, tamird reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 10 unresolved discussions (waiting on @vadorovsky)

___
*[`src/llvm/mod.rs` line 3 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9PlhEJ2KhLkqdkVn:-OCioVeV8ofhAdCFsE2Z:b9zfinl) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/mod.rs#L3)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

I did that to be able to import `use crate::llvm::types::LLVMTypeError` outside of llvm module.
</blockquote></details>

maybe `pub use llvm::types::LLVMTypeError` would be better?
___
*[`src/llvm/types/ir.rs` line 240 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCiA1cX9HulhNCmgA1J:-OCio8Nt3a9zkJ3bb4oJ:b-dsa9pe) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L240)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

To put it in easier words:

- I'm panicking when I'm sure that caller's input can't result in getting a `nullptr`.
- I'm returning the error when there is no such guarantee.
</blockquote></details>

Thanks for explaining. I thought there was the guarantee here, but I understand now that there isn't.
___
*[`src/llvm/types/ir.rs` line 359 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi83bm-j6tzEd2zTAT:-OCj1e0j2f5JWZRfb9yR:b-916wt5) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/ir.rs#L359)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

To put it in easier words - `LLVMGetSubprogram`/`Function::getSubprogram` tolerates the case when the given function has no subprogram.
</blockquote></details>

Yeah, that's fine, I was just pointing out that the responsibility for checking for null is bleeding across the boundary. Hopefully my other suggestion will clean all this up.
___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCiod38Czt7RNIw5Rb2:bxl2kn9) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
> BTW, my long-term intention is to wrap absolutely every type and remove the direct `from_ptr` usage, especially in `src/linker/di.rs`.

Sounds great to me.
___
*[`src/llvm/types/mod.rs` line 20 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi4NB7BSggagrna8JI:-OCioP-z-cffX39n6Lg9:b-nav911) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L20)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Yeah, removing that bound results in this error:

```
   Compiling bpf-linker v0.9.13 (/home/vadorovsky/src/bpf-linker)
error[E0277]: the size for values of type `Self` cannot be known at compilation time
   --> src/llvm/types/mod.rs:18:39
    |
18  |     fn from_ptr(ptr: Self::Target) -> Result<Self, LLVMTypeError>;
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
note: required by an implicit `Sized` bound in `Result`
   --> /home/vadorovsky/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/lib/rustlib/src/rust/library/core/src/result.rs:528:17
    |
528 | pub enum Result<T, E> {
    |                 ^ required by the implicit `Sized` requirement on this type parameter in `Result`
help: consider further restricting `Self`
    |
18  |     fn from_ptr(ptr: Self::Target) -> Result<Self, LLVMTypeError> where Self: Sized;
```
</blockquote></details>

Thanks for checking.


<!-- Sent from Reviewable.io -->

2024-11-27 19:31 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 10 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/types/mod.rs` line 9 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi6xrd85-wkwmwDTcS:-OCj3s9D6CgEIw29m178:b-oelq31) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L9)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: maybe we can use TypeId here? https://doc.rust-lang.org/stable/std/any/struct.TypeId.html

EDIT: seems like no because there are sometimes multiple admissible types, but i think we do want the unexpected type to be shown
</blockquote></details>

What's a bit tricky (both about using TypeId and showing the unexpected type) is that we don't cover all IR/DI types from LLVM. We define only the ones we need.

I'm open for ideas, but for now the only one coming to my mind is having two type variants, maybe something like

```rust
pub enum LLVMTypeError {
    #[error("invalid pointer type, expected {0}, got {0}")]
    InvalidPointerType(TypeId, TypeId),
    #[error("unknown pointer type, expected {0}")]
    UnknownPointerType(TypeId),
}
```


<!-- Sent from Reviewable.io -->

2024-11-29 11:32 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 10 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/di.rs` line 340 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9FAd4tqfJ7yakN6d:-OCj6zt14oy4f7lRl6FM:b-1rftdh) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/di.rs#L340)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

instead of this, we should push the LLVMTypeWrapper::from_ptr call into the `llvm_iterator!` macro.
</blockquote></details>

I love the idea, just - I would need to port all iterators to use LLVMTypeWrapper.  Some types (like 
___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCrftlZ8It8Y9cjNnar:b-4yh6mi) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> BTW, my long-term intention is to wrap absolutely every type and remove the direct `from_ptr` usage, especially in `src/linker/di.rs`.

Sounds great to me.
</blockquote></details>

Actually, does it have to be as complicated as in your snippet?

This code compiles:

```rust
pub trait LLVMTypeWrapper {
    type Target: Sized;

    /// Constructs a new [`Self`] from the given pointer `ptr`.
    fn from_ptr(ptr: NonNull<Self::Target>) -> Result<Self, LLVMTypeError>
    where
        Self: Sized;
    fn as_ptr(&self) -> Self::Target;
}
```

And I think it's correct. It takes `NonNull` during the wrapper initialization. It returns just a raw pointer when requested.


<!-- Sent from Reviewable.io -->

2024-11-29 11:40 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 10 unresolved discussions (waiting on @tamird)

___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCrhfL61QQPDTKFBptJ:bhs7j3e) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Actually, does it have to be as complicated as in your snippet?

This code compiles:

```rust
pub trait LLVMTypeWrapper {
    type Target: Sized;

    /// Constructs a new [`Self`] from the given pointer `ptr`.
    fn from_ptr(ptr: NonNull<Self::Target>) -> Result<Self, LLVMTypeError>
    where
        Self: Sized;
    fn as_ptr(&self) -> Self::Target;
}
```

And I think it's correct. It takes `NonNull` during the wrapper initialization. It returns just a raw pointer when requested.
</blockquote></details>

This trick should work if I use the non-ref types from llvm-sys. So basically, instead of using `LLVMValueRef` (which is an alias to `*mut LLVMValue`), I could define `type Target = LLVMValue`, which would result in `NonNull<LLVMValue>`

And ofc `as_ptr` would need to return `*mut Self::Target`, sorry for the mistake in my snipper.


<!-- Sent from Reviewable.io -->

2024-11-29 13:41 UTC, tamird reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/bpf-linker/223)* status: all files reviewed, 10 unresolved discussions (waiting on @vadorovsky)

___
*[`src/llvm/di.rs` line 340 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi9FAd4tqfJ7yakN6d:-OCs8Ylu7qAX9WUBuyjj:b-sg76gc) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/di.rs#L340)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

I love the idea, just - I would need to port all iterators to use LLVMTypeWrapper.  Some types (like
</blockquote></details>

Comment cut off?
___
*[`src/llvm/types/mod.rs` line 11 at r3](https://reviewable.io/reviews/aya-rs/bpf-linker/223#-OCi667e8VFgxFMFkgFD:-OCs8gyQ8B3CemLFD8U1:bi36t63) ([raw file](https://github.com/aya-rs/bpf-linker/blob/91d841299336b819a17ce50f38cec66965ef2f9a/src/llvm/types/mod.rs#L11)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

This trick should work if I use the non-ref types from llvm-sys. So basically, instead of using `LLVMValueRef` (which is an alias to `*mut LLVMValue`), I could define `type Target = LLVMValue`, which would result in `NonNull<LLVMValue>`

And ofc `as_ptr` would need to return `*mut Self::Target`, sorry for the mistake in my snipper.
</blockquote></details>

I think in reality you can never get your hands on a non-ref type. See [`LLVMValue`](https://docs.rs/llvm-sys/latest/llvm_sys/enum.LLVMValue.html) which is an uninhabitable type.

But if you can, great. The only reason for my complicated snippet is indeed to get at the pointed-to type from the pointer type.


<!-- Sent from Reviewable.io -->

2025-10-01 12:50 UTC, vadorovsky commented
The most of related work was done better in #295.

2025-10-01 12:50 UTC, closed without merging