Change the type of LLVM Message pointer to libc :: c_char
aya-rs/bpf-linker pull request #8
Opened 2021-12-07 06:58 UTC by ken109

When I tried to install it on Ubuntu, I got the following error.

```
error[E0308]: mismatched types
  --> src/llvm/message.rs:34:36
   |
34 |                 LLVMDisposeMessage(self.ptr);
   |                                    ^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*mut i8`

error[E0308]: mismatched types
  --> src/llvm/message.rs:43:52
   |
43 |             let contents = unsafe { CStr::from_ptr(self.ptr).to_str().unwrap() };
   |                                                    ^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*mut i8`

// Many others
```

The reason was that the arguments of LLVMDisposeMessage and LLVMCreateBinary are libc :: c_char type instead of i8 type.

2021-12-18 05:20 UTC, alessandrod requested changes
Thank you and sorry for the wait! This slipped under my radar. See my comments.

2021-12-18 05:20 UTC, alessandrod commented on src/lib.rs
> +extern crate libc;
I don't think this is needed?

2021-12-18 05:20 UTC, alessandrod commented on src/llvm/message.rs
> +    pub ptr: *mut ::libc::c_char,
add a `use libc::c_char;` declaration at the top and use `c_char` here and in other places please

2022-01-11 06:05 UTC, ken109 commented
@alessandrod 
Fixed!

2022-01-21 11:26 UTC, merged

2022-01-21 11:26 UTC, alessandrod commented
Thank you!